version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /srv/e6f583e0-1144-4062-bca6-9bb7e8760523/media:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_GID=100
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /srv/e6f583e0-1144-4062-bca6-9bb7e8760523/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}